Falsepine: NodeAI.NodeAI_Senses Class Reference
NodeAI.NodeAI_Senses Class Reference
A class which gives a NodeAI_Agent sensory awareness.
Public Types
enum BoneDirection {
Forward , Right , Left , Up ,
Back , Down
}
The direction of the bone which is used to represent the Agent's eyes.
Public Member Functions
delegate void SensoryEventHandler (SensoryEvent e)
The delegate for handling sensory events.
void RegisterSensoryEvent (GameObject source, GameObject target, float urgency, SensoryEvent.SenseType type)
Registers a sensory event with the Agent.
bool CanSee (GameObject target)
Returns true if the Agent can see the target.
bool CanSeeTag (string tag)
Checks if the Agent can see an object with the given tag.
bool IsAwareOf (GameObject target)
Check if the Agent is currently aware of the target.
bool IsAwareOfTag (string tag)
Checks if the Agent is currently aware of an object with the given tag.
GameObject GetAwareObjectWithTag (string tag)
Returns the list of objects which the Agent can see with the given tag.
GameObject[] GetVisibleObjects ()
Returns the list of objects which the Agent can see.
void OnDrawGizmosSelected ()
Draws the vision cone of the Agent.
Public Attributes
Transform eyesBone
The transform of the bone which is used to represent the Agent's eyes.
float maxHearingRange = 10
The maximum range of the Agent's hearing.
BoneDirection eyeDirection
The direction of the bone which is used to represent the Agent's eyes.
float sightDistance = 10f
The distance of the Agent's vision cone.
float sightAngle = 90f
The angle of the Agent's vision cone.
LayerMask sightMask
The layer mask of the layers which the Agent's vision cone can see.
Events
SensoryEventHandler OnSensoryEvent
The event for handling sensory events.
Private Member Functions
void Start ()
void DebugSense (SensoryEvent e)
A debug function to investigate the sensory events.
void Update ()
Private Attributes
List< SensoryEvent > sensoryEvents = new List<SensoryEvent>()
The list of sensory events.
List< GameObject > noticedObjects = new List<GameObject>()
The list of objects which the Agent has noticed.
Vector3 eyesForward
The direction representing the forward direction of the Agent's eyes. This is used to correct the position of the vision cone when the bone on the model is oriented strangely.
Detailed Description
A class which gives a NodeAI_Agent sensory awareness.
This class is responsible for giving the NodeAI_Agent sensory awareness of its environment and things that happen to it. When placed on a GameObject with a NodeAI_Agent component, the NodeAI_Agent will be able to perceive things in the environment. The Agent will automatically be able to percieve things visually, but auditory and somatic sensory data must be added manually.
For example, the following features could be implemented using auditory or somatic sensory events:
Hearing the player's footsteps The script on the player used to play footstep sounds could register auditory events on any nearby Agents, allowing them to become aware of the player if footsteps are heard.
Touching a hazard A Hazardous area could register a somatic event on any agents which collide with it, and the agent could react to it accordingly by moving away from the hazard.
Definition at line 97 of file NodeAI_Senses.cs.
Member Enumeration Documentation
BoneDirection
enum NodeAI.NodeAI_Senses.BoneDirection
The direction of the bone which is used to represent the Agent's eyes.
Enumerator
Forward
The bone is oriented forward.
Right
The bone is oriented to the right.
Left
The bone is oriented to the left.
Up
The bone is oriented upwards.
Back
The bone is oriented backwards.
Down
The bone is oriented downwards.
Definition at line 126 of file NodeAI_Senses.cs.
Member Function Documentation
CanSee()
bool NodeAI.NodeAI_Senses.CanSee (GameObject target) inline
Returns true if the Agent can see the target.
Parameters
target The target to check.
Returns
True if the Agent can see the target.
Definition at line 228 of file NodeAI_Senses.cs.
Referenced by NodeAI.Senses.CanSee.Eval().
CanSeeTag()
bool NodeAI.NodeAI_Senses.CanSeeTag (string tag) inline
Checks if the Agent can see an object with the given tag.
Parameters
tag The tag of the object to check.
Returns
True if the Agent can see an object with the given tag.
Parameters
tag Returns true if the Agent can see an object with the given tag.
Definition at line 238 of file NodeAI_Senses.cs.
Referenced by NodeAI.Senses.CanSeeTag.Eval().
DebugSense()
void NodeAI.NodeAI_Senses.DebugSense (SensoryEvent e) inline private
A debug function to investigate the sensory events.
Parameters
e The SensoryEvent
Definition at line 154 of file NodeAI_Senses.cs.
References NodeAI.NodeAI_Senses.eyesBone, and NodeAI.SensoryEvent.source.
GetAwareObjectWithTag()
GameObject NodeAI.NodeAI_Senses.GetAwareObjectWithTag (string tag) inline
Returns the list of objects which the Agent can see with the given tag.
Parameters
tag The tag of the objects to check.
Returns
The list of objects which the Agent can see with the given tag.
Parameters
tag Returns the first object with the given tag which the Agent is aware of.
Definition at line 272 of file NodeAI_Senses.cs.
Referenced by NodeAI.Senses.FindTagInKnownObjects.GetNewValues().
GetVisibleObjects()
GameObject[] NodeAI.NodeAI_Senses.GetVisibleObjects () inline
Returns the list of objects which the Agent can see.
Returns
The list of objects which the Agent can see.
Definition at line 281 of file NodeAI_Senses.cs.
IsAwareOf()
bool NodeAI.NodeAI_Senses.IsAwareOf (GameObject target) inline
Check if the Agent is currently aware of the target.
Parameters
target The target to check.
Returns
True if the Agent is currently aware of the target.
Parameters
target Returns true if the Agent is aware of the target.
Definition at line 248 of file NodeAI_Senses.cs.
Referenced by NodeAI.Senses.IsAwareOfObject.Eval().
IsAwareOfTag()
bool NodeAI.NodeAI_Senses.IsAwareOfTag (string tag) inline
Checks if the Agent is currently aware of an object with the given tag.
Parameters
tag The tag of the object to check.
Returns
True if the Agent is currently aware of an object with the given tag.
Parameters
tag Returns true if the Agent is aware of an object with the given tag.
Definition at line 262 of file NodeAI_Senses.cs.
OnDrawGizmosSelected()
void NodeAI.NodeAI_Senses.OnDrawGizmosSelected () inline
Draws the vision cone of the Agent.
Definition at line 325 of file NodeAI_Senses.cs.
References NodeAI.CustomGizmos.DrawCone().
RegisterSensoryEvent()
void NodeAI.NodeAI_Senses.RegisterSensoryEvent (GameObject source, GameObject target, float urgency, SensoryEvent.SenseType type) inline
Registers a sensory event with the Agent.
Parameters
source The source of the event.
target The target of the event.
urgency The urgency of the event.
senseType The type of the event.
The source and target of the event must be GameObjects.
Parameters
type Registers a sensory event.
Definition at line 115 of file NodeAI_Senses.cs.
References NodeAI.NodeAI_Senses.OnSensoryEvent, and NodeAI.NodeAI_Senses.sensoryEvents.
SensoryEventHandler()
delegate void NodeAI.NodeAI_Senses.SensoryEventHandler (SensoryEvent e)
The delegate for handling sensory events.
Start()
void NodeAI.NodeAI_Senses.Start () inline private
Definition at line 145 of file NodeAI_Senses.cs.
Update()
void NodeAI.NodeAI_Senses.Update () inline private
Definition at line 160 of file NodeAI_Senses.cs.
Member Data Documentation
eyeDirection
BoneDirection NodeAI.NodeAI_Senses.eyeDirection
The direction of the bone which is used to represent the Agent's eyes.
Definition at line 136 of file NodeAI_Senses.cs.
eyesBone
Transform NodeAI.NodeAI_Senses.eyesBone
The transform of the bone which is used to represent the Agent's eyes.
Definition at line 123 of file NodeAI_Senses.cs.
Referenced by NodeAI.NodeAI_Senses.DebugSense().
eyesForward
Vector3 NodeAI.NodeAI_Senses.eyesForward private
The direction representing the forward direction of the Agent's eyes. This is used to correct the position of the vision cone when the bone on the model is oriented strangely.
Definition at line 122 of file NodeAI_Senses.cs.
maxHearingRange
float NodeAI.NodeAI_Senses.maxHearingRange = 10
The maximum range of the Agent's hearing.
Definition at line 124 of file NodeAI_Senses.cs.
noticedObjects
List<GameObject> NodeAI.NodeAI_Senses.noticedObjects = new List<GameObject>() private
The list of objects which the Agent has noticed.
Definition at line 103 of file NodeAI_Senses.cs.
sensoryEvents
List<SensoryEvent> NodeAI.NodeAI_Senses.sensoryEvents = new List<SensoryEvent>() private
The list of sensory events.
Definition at line 102 of file NodeAI_Senses.cs.
Referenced by NodeAI.NodeAI_Senses.RegisterSensoryEvent().
sightAngle
float NodeAI.NodeAI_Senses.sightAngle = 90f
The angle of the Agent's vision cone.
Definition at line 139 of file NodeAI_Senses.cs.
sightDistance
float NodeAI.NodeAI_Senses.sightDistance = 10f
The distance of the Agent's vision cone.
Definition at line 138 of file NodeAI_Senses.cs.
sightMask
LayerMask NodeAI.NodeAI_Senses.sightMask
The layer mask of the layers which the Agent's vision cone can see.
Definition at line 141 of file NodeAI_Senses.cs.
Event Documentation
OnSensoryEvent
SensoryEventHandler NodeAI.NodeAI_Senses.OnSensoryEvent
The event for handling sensory events.
Definition at line 101 of file NodeAI_Senses.cs.
Referenced by NodeAI.NodeAI_Senses.RegisterSensoryEvent().
The documentation for this class was generated from the following file:
Assets/NodeAIv2/Runtime/NodeAI_Senses.cs