Falsepine: ItemDatabase Class Reference
ItemDatabase Class Reference
Static Public Member Functions
static Item GetItem (string id)
Gets an item by its id.
static List< Item > GetItemsById (string _id)
get list of items in the database by id
static List< Item > GetItemsByName (string _name)
get list of items in the database by name
static List< Item > GetItemsByDescription (string _description)
get list of items in the database by description
static List< Item > GetItemsByType (System.Type _type)
get list of items in the database by type (System.Type)
static List< Item > GetItemsByType (string _type)
get list of items in the database by type (string)
NOTE: Case sensitive!
static List< Item > GetItemsByORFilter (string _id="", string _name="", string _description="", string _type_s="", System.Type _type_t=null)
get list of items in the database using optional search parameters using OR logic
static List< Item > GetItemsByANDFilter (string _id="", string _name="", string _description="", string _type_s="", System.Type _type_t=null)
get list of items in the database using optional search parameters using AND logic
static string GetDatabaseFolderNames ()
static string GetDatabaseFoldersPath ()
static void Initialize ()
static void SaveListToFile ()
Saves the database to file from memory.
static void LoadListFromFile ()
Loads the database from file into memory
static void DeleteListFromFile ()
Deletes all .json files in the database folder
static void DeleteListMetaDataFromFile ()
Deletes meta data files in the database folder
static void CleanUpFiles ()
static void ResetDatabaseFolder ()
Resets the database folder
static void Refresh ()
static void ValidateIDs ()
Validates all item ids.
Static Public Attributes
static List< Item > database = new List<Item>()
Detailed Description
Definition at line 19 of file ItemDatabase.cs.
Constructor & Destructor Documentation
ItemDatabase()
static ItemDatabase.ItemDatabase () inline static private
Definition at line 22 of file ItemDatabase.cs.
Member Function Documentation
CleanUpFiles()
static void ItemDatabase.CleanUpFiles () inline static
Definition at line 339 of file ItemDatabase.cs.
DeleteListFromFile()
static void ItemDatabase.DeleteListFromFile () inline static
Deletes all .json files in the database folder
Definition at line 296 of file ItemDatabase.cs.
Referenced by ResetDatabaseFolder().
DeleteListMetaDataFromFile()
static void ItemDatabase.DeleteListMetaDataFromFile () inline static
Deletes meta data files in the database folder
Definition at line 319 of file ItemDatabase.cs.
Referenced by ResetDatabaseFolder().
GetDatabaseFolderNames()
static string ItemDatabase.GetDatabaseFolderNames () inline static
Definition at line 192 of file ItemDatabase.cs.
GetDatabaseFoldersPath()
static string ItemDatabase.GetDatabaseFoldersPath () inline static
Definition at line 197 of file ItemDatabase.cs.
GetItem()
static Item ItemDatabase.GetItem (string id) inline static
Gets an item by its id.
Parameters
id The id of the item.
Returns
The item with the given id.
Definition at line 36 of file ItemDatabase.cs.
Referenced by Inventory.TryAddItemToInventory().
GetItemsByANDFilter()
static List< Item > ItemDatabase.GetItemsByANDFilter (string _id = "", string _name = "", string _description = "", string _type_s = "", System.Type _type_t = null) inline static
get list of items in the database using optional search parameters using AND logic
Definition at line 142 of file ItemDatabase.cs.
References GetItemsByDescription(), GetItemsById(), GetItemsByName(), and GetItemsByType().
GetItemsByDescription()
static List< Item > ItemDatabase.GetItemsByDescription (string _description) inline static
get list of items in the database by description
Definition at line 65 of file ItemDatabase.cs.
Referenced by GetItemsByANDFilter(), and GetItemsByORFilter().
GetItemsById()
static List< Item > ItemDatabase.GetItemsById (string _id) inline static
get list of items in the database by id
Definition at line 49 of file ItemDatabase.cs.
Referenced by GetItemsByANDFilter(), and GetItemsByORFilter().
GetItemsByName()
static List< Item > ItemDatabase.GetItemsByName (string _name) inline static
get list of items in the database by name
Definition at line 57 of file ItemDatabase.cs.
Referenced by GetItemsByANDFilter(), and GetItemsByORFilter().
GetItemsByORFilter()
static List< Item > ItemDatabase.GetItemsByORFilter (string _id = "", string _name = "", string _description = "", string _type_s = "", System.Type _type_t = null) inline static
get list of items in the database using optional search parameters using OR logic
Definition at line 90 of file ItemDatabase.cs.
References GetItemsByDescription(), GetItemsById(), GetItemsByName(), and GetItemsByType().
GetItemsByType() [1/2]
static List< Item > ItemDatabase.GetItemsByType (string _type) inline static
get list of items in the database by type (string)
NOTE: Case sensitive!
Definition at line 82 of file ItemDatabase.cs.
GetItemsByType() [2/2]
static List< Item > ItemDatabase.GetItemsByType (System.Type _type) inline static
get list of items in the database by type (System.Type)
Definition at line 73 of file ItemDatabase.cs.
Referenced by GetItemsByANDFilter(), and GetItemsByORFilter().
Initialize()
static void ItemDatabase.Initialize () inline static
Definition at line 202 of file ItemDatabase.cs.
LoadListFromFile()
static void ItemDatabase.LoadListFromFile () inline static
Loads the database from file into memory
Definition at line 273 of file ItemDatabase.cs.
References Item.Load().
Refresh()
static void ItemDatabase.Refresh () inline static
Definition at line 438 of file ItemDatabase.cs.
ResetDatabaseFolder()
static void ItemDatabase.ResetDatabaseFolder () inline static
Resets the database folder
Definition at line 429 of file ItemDatabase.cs.
References DeleteListFromFile(), DeleteListMetaDataFromFile(), and SaveListToFile().
SaveListToFile()
static void ItemDatabase.SaveListToFile () inline static
Saves the database to file from memory.
Definition at line 255 of file ItemDatabase.cs.
References Item.Save().
Referenced by ResetDatabaseFolder().
ValidateIDs()
static void ItemDatabase.ValidateIDs () inline static
Validates all item ids.
Definition at line 489 of file ItemDatabase.cs.
References ValidateIDs().
Referenced by ValidateIDs().
Member Data Documentation
database
List<Item> ItemDatabase.database = new List<Item>() static
Definition at line 29 of file ItemDatabase.cs.
The documentation for this class was generated from the following file:
Assets/ItemDatabaseTool/Scripts/ItemDatabase.cs