Falsepine: NodeAI.GraphView Class Reference
NodeAI.GraphView Class Reference
The GraphView is used to display the NodeAI Graph and handle user input.
Public Member Functions
GraphView ()
This function is called when the GraphView is created.
void AddBlackboardSearchWindow (Vector2 position)
Adds the blackboard search window
void CreateGroup (string name, List< Node > nodes)
Greate a Group
void AddEntryNode ()
Adds an entrypoint to the graph
Node GenerateQueryNode (string name, Query query, Vector2 position)
Generates a Query node
Node ContextCreateNode (Node parent, NodeData.Type type, string name, RuntimeBase logic)
Creates a node from the context menu
Node GenerateNode (NodeData data)
Generates a node from serialized data
Node GenerateNode (NodeData.Type nodeType, string name, RuntimeBase logic)
Generate a Node
override List< Port > GetCompatiblePorts (Port startPort, NodeAdapter nodeAdapter)
Gets a list of all compatible ports in the graph
void AddPropertyToBlackboard (NodeData.Property exposedProperty)
Adds a property to the blackboard
Public Attributes
List< NodeData.Property > exposedProperties = new List<NodeData.Property>()
List of all exposed properties in the behaviour.
Blackboard blackboard
The blackboard that is used to store parameters.
Node currHoveredNode
The node that is currently hovered.
Private Member Functions
void AddSearchWindow (Vector2 position)
Add the search window
void GroupNodes ()
Group selected nodes
void UngroupNodes ()
Ungroup selected nodes
void UnlinkAndRemove (Node n)
Unlink selected nodes from each other and remove them from the graph
void UnlinkAndRemove (Edge e)
Remove selected edges from the graph
void RemoveSelectedNodes ()
Remove selected nodes from the graph
void RemoveSelectedEdges ()
Remove selected edges from the graph
void HandleDragEndEvent (DragPerformEvent e)
Handles event called when an element is dragged and dropped
void HandleMouseDownEvents (MouseDownEvent e)
Handles right click events
void HandleMouseOverEvent (MouseOverEvent e)
Handles mouse hover events
void HandleMouseLeaveEvent (MouseLeaveEvent e)
Handles event called when the mouse leaves an element
Port GeneratePort (Node node, Direction dir, Port.Capacity capacity=Port.Capacity.Single)
Generates a port for a node
Node GenerateParameterNode (string paramReference, System.Type paramType, Vector2 position)
Generates a node for a parameter
Node GenerateEntryPointNode ()
Generates an entrypoint node
void AddPropertyField (Node node, NodeData.SerializableProperty property, RuntimeBase logic)
Adds a Property Field to a Node
void AddPropertyField (Node node, NodeData.SerializableProperty property, Query query)
Add a property field to a node
Private Attributes
SearchWindow searchWindow
The search window that is used to search for nodes.
BlackboardSearchWindow blackboardSearchWindow
The search window that is used to search for blackboard parameters.
QuerySearchWindow querySearchWindow
The search window that is used to search for queries.
Detailed Description
The GraphView is used to display the NodeAI Graph and handle user input.
Definition at line 30 of file GraphView.cs.
Constructor & Destructor Documentation
GraphView()
NodeAI.GraphView.GraphView () inline
This function is called when the GraphView is created.
Definition at line 43 of file GraphView.cs.
References NodeAI.GraphView.blackboardSearchWindow, NodeAI.GraphView.HandleDragEndEvent(), NodeAI.GraphView.HandleMouseDownEvents(), NodeAI.GraphView.HandleMouseLeaveEvent(), NodeAI.GraphView.HandleMouseOverEvent(), NodeAI.BlackboardSearchWindow.Init(), NodeAI.QuerySearchWindow.Init(), NodeAI.SearchWindow.Init(), NodeAI.GraphView.querySearchWindow, and NodeAI.GraphView.searchWindow.
Member Function Documentation
AddBlackboardSearchWindow()
void NodeAI.GraphView.AddBlackboardSearchWindow (Vector2 position) inline
Adds the blackboard search window
Parameters
position
Definition at line 89 of file GraphView.cs.
References NodeAI.GraphView.blackboardSearchWindow.
Referenced by NodeAI.Graph.GenerateBlackboard().
AddEntryNode()
void NodeAI.GraphView.AddEntryNode () inline
Adds an entrypoint to the graph
Definition at line 290 of file GraphView.cs.
References NodeAI.GraphView.GenerateEntryPointNode().
Referenced by NodeAI.Graph.CreateNewBehaviour().
AddPropertyField() [1/2]
void NodeAI.GraphView.AddPropertyField (Node node, NodeData.SerializableProperty property, Query query) inline private
Add a property field to a node
Parameters
node
property
query
Definition at line 938 of file GraphView.cs.
References NodeAI.GraphView.GeneratePort(), NodeAI.Node.inputPorts, NodeAI.Node.nodeType, NodeAI.Node.outputPort, NodeAI.Node.outputPorts, and NodeAI.Query.SetProperty().
AddPropertyField() [2/2]
void NodeAI.GraphView.AddPropertyField (Node node, NodeData.SerializableProperty property, RuntimeBase logic) inline private
Adds a Property Field to a Node
Parameters
node
property
logic
Definition at line 754 of file GraphView.cs.
References NodeAI.GraphView.GeneratePort(), NodeAI.Query.GetProperties(), NodeAI.Node.inputPorts, NodeAI.Node.outputPort, NodeAI.Node.outputPorts, NodeAI.Node.query, and NodeAI.RuntimeBase.SetProperty().
Referenced by NodeAI.GraphView.GenerateNode(), and NodeAI.GraphView.GenerateQueryNode().
AddPropertyToBlackboard()
void NodeAI.GraphView.AddPropertyToBlackboard (NodeData.Property exposedProperty) inline
Adds a property to the blackboard
Parameters
exposedProperty
Definition at line 1141 of file GraphView.cs.
References NodeAI.GraphView.exposedProperties, NodeAI.NodeData.Property< T >.GUID, NodeAI.NodeData.Property< T >.name, and NodeAI.NodeData.Property< T >.type.
Referenced by NodeAI.Serializer.Deserialize(), and NodeAI.BlackboardSearchWindow.OnSelectEntry().
AddSearchWindow()
void NodeAI.GraphView.AddSearchWindow (Vector2 position) inline private
Add the search window
Parameters
position
Definition at line 78 of file GraphView.cs.
References NodeAI.GraphView.searchWindow.
Referenced by NodeAI.GraphView.GenerateEntryPointNode(), and NodeAI.GraphView.GenerateNode().
ContextCreateNode()
Node NodeAI.GraphView.ContextCreateNode (Node parent, NodeData.Type type, string name, RuntimeBase logic) inline
Creates a node from the context menu
Parameters
parent
type
name
logic
Returns
Definition at line 409 of file GraphView.cs.
References NodeAI.GraphView.GenerateNode(), NodeAI.Node.inputPort, NodeAI.Node.outputPort, and NodeAI.RuntimeBase.tooltip.
Referenced by NodeAI.SearchWindow.OnSelectEntry().
CreateGroup()
void NodeAI.GraphView.CreateGroup (string name, List< Node > nodes) inline
Greate a Group
Parameters
name
nodes
Definition at line 122 of file GraphView.cs.
Referenced by NodeAI.Serializer.Deserialize().
GenerateEntryPointNode()
Node NodeAI.GraphView.GenerateEntryPointNode () inline private
Generates an entrypoint node
Returns
Definition at line 364 of file GraphView.cs.
References NodeAI.GraphView.AddSearchWindow(), NodeAI.GraphView.GeneratePort(), and NodeAI.Node.outputPort.
Referenced by NodeAI.GraphView.AddEntryNode().
GenerateNode() [1/2]
Node NodeAI.GraphView.GenerateNode (NodeData data) inline
Generates a node from serialized data
Parameters
data
Returns
Definition at line 480 of file GraphView.cs.
References NodeAI.GraphView.AddPropertyField(), NodeAI.GraphView.AddSearchWindow(), NodeAI.GraphView.exposedProperties, NodeAI.GraphView.GeneratePort(), NodeAI.Query.GetProperties(), NodeAI.RuntimeBase.GetProperties(), NodeAI.NodeData.GUID, NodeAI.Node.inputPort, NodeAI.Node.nodeType, NodeAI.NodeData.nodeType, NodeAI.Node.outputPort, NodeAI.NodeData.parentGUID, NodeAI.NodeData.position, NodeAI.Node.query, NodeAI.NodeData.query, NodeAI.Node.runtimeLogic, NodeAI.NodeData.runtimeLogic, NodeAI.GraphView.searchWindow, NodeAI.SearchWindow.SetSelectedNode(), NodeAI.NodeData.title, and NodeAI.RuntimeBase.tooltip.
Referenced by NodeAI.GraphView.ContextCreateNode(), and NodeAI.Serializer.Deserialize().
GenerateNode() [2/2]
Node NodeAI.GraphView.GenerateNode (NodeData.Type nodeType, string name, RuntimeBase logic) inline
Generate a Node
Parameters
nodeType
name
logic
Returns
Definition at line 637 of file GraphView.cs.
References NodeAI.GraphView.AddPropertyField(), NodeAI.GraphView.AddSearchWindow(), NodeAI.GraphView.GeneratePort(), NodeAI.RuntimeBase.GetProperties(), NodeAI.Node.inputPort, NodeAI.Node.nodeType, NodeAI.Node.outputPort, NodeAI.GraphView.searchWindow, and NodeAI.SearchWindow.SetSelectedNode().
GenerateParameterNode()
Node NodeAI.GraphView.GenerateParameterNode (string paramReference, System.Type paramType, Vector2 position) inline private
Generates a node for a parameter
Parameters
paramReference
paramType
position
Returns
Definition at line 314 of file GraphView.cs.
References NodeAI.GraphView.exposedProperties, NodeAI.GraphView.GeneratePort(), and NodeAI.Node.outputPort.
Referenced by NodeAI.GraphView.HandleDragEndEvent().
GeneratePort()
Port NodeAI.GraphView.GeneratePort (Node node, Direction dir, Port.Capacity capacity = Port.Capacity.Single) inline private
Generates a port for a node
Parameters
node
dir
capacity
Returns
Definition at line 302 of file GraphView.cs.
Referenced by NodeAI.GraphView.AddPropertyField(), NodeAI.GraphView.GenerateEntryPointNode(), NodeAI.GraphView.GenerateNode(), and NodeAI.GraphView.GenerateParameterNode().
GenerateQueryNode()
Node NodeAI.GraphView.GenerateQueryNode (string name, Query query, Vector2 position) inline
Generates a Query node
Parameters
name
query
position
Returns
Definition at line 340 of file GraphView.cs.
References NodeAI.GraphView.AddPropertyField(), and NodeAI.Query.GetProperties().
Referenced by NodeAI.QuerySearchWindow.OnSelectEntry().
GetCompatiblePorts()
override List< Port > NodeAI.GraphView.GetCompatiblePorts (Port startPort, NodeAdapter nodeAdapter) inline
Gets a list of all compatible ports in the graph
Parameters
startPort
nodeAdapter
Returns
Definition at line 1122 of file GraphView.cs.
GroupNodes()
void NodeAI.GraphView.GroupNodes () inline private
Group selected nodes
Definition at line 98 of file GraphView.cs.
Referenced by NodeAI.GraphView.HandleMouseDownEvents().
HandleDragEndEvent()
void NodeAI.GraphView.HandleDragEndEvent (DragPerformEvent e) inline private
Handles event called when an element is dragged and dropped
Parameters
e
Definition at line 207 of file GraphView.cs.
References NodeAI.GraphView.exposedProperties, NodeAI.GraphView.GenerateParameterNode(), NodeAI.NodeData.SerializableProperty.GUID, and NodeAI.NodeData.SerializableProperty.type.
Referenced by NodeAI.GraphView.GraphView().
HandleMouseDownEvents()
void NodeAI.GraphView.HandleMouseDownEvents (MouseDownEvent e) inline private
Handles right click events
Parameters
e
Definition at line 222 of file GraphView.cs.
References NodeAI.GraphView.GroupNodes(), NodeAI.GraphView.querySearchWindow, NodeAI.GraphView.RemoveSelectedEdges(), NodeAI.GraphView.RemoveSelectedNodes(), and NodeAI.GraphView.UngroupNodes().
Referenced by NodeAI.GraphView.GraphView().
HandleMouseLeaveEvent()
void NodeAI.GraphView.HandleMouseLeaveEvent (MouseLeaveEvent e) inline private
Handles event called when the mouse leaves an element
Parameters
e
Definition at line 278 of file GraphView.cs.
References NodeAI.GraphView.currHoveredNode.
Referenced by NodeAI.GraphView.GraphView().
HandleMouseOverEvent()
void NodeAI.GraphView.HandleMouseOverEvent (MouseOverEvent e) inline private
Handles mouse hover events
Parameters
e
Definition at line 255 of file GraphView.cs.
References NodeAI.GraphView.currHoveredNode, and NodeAI.Node.outputPort.
Referenced by NodeAI.GraphView.GraphView().
RemoveSelectedEdges()
void NodeAI.GraphView.RemoveSelectedEdges () inline private
Remove selected edges from the graph
Definition at line 196 of file GraphView.cs.
References NodeAI.GraphView.UnlinkAndRemove().
Referenced by NodeAI.GraphView.HandleMouseDownEvents().
RemoveSelectedNodes()
void NodeAI.GraphView.RemoveSelectedNodes () inline private
Remove selected nodes from the graph
Definition at line 187 of file GraphView.cs.
References NodeAI.GraphView.UnlinkAndRemove().
Referenced by NodeAI.GraphView.HandleMouseDownEvents().
UngroupNodes()
void NodeAI.GraphView.UngroupNodes () inline private
Ungroup selected nodes
Definition at line 139 of file GraphView.cs.
Referenced by NodeAI.GraphView.HandleMouseDownEvents().
UnlinkAndRemove() [1/2]
void NodeAI.GraphView.UnlinkAndRemove (Edge e) inline private
Remove selected edges from the graph
Parameters
e
Definition at line 177 of file GraphView.cs.
UnlinkAndRemove() [2/2]
void NodeAI.GraphView.UnlinkAndRemove (Node n) inline private
Unlink selected nodes from each other and remove them from the graph
Parameters
n
Definition at line 160 of file GraphView.cs.
Referenced by NodeAI.GraphView.RemoveSelectedEdges(), and NodeAI.GraphView.RemoveSelectedNodes().
Member Data Documentation
blackboard
Blackboard NodeAI.GraphView.blackboard
The blackboard that is used to store parameters.
Definition at line 36 of file GraphView.cs.
Referenced by NodeAI.Serializer.Deserialize().
blackboardSearchWindow
BlackboardSearchWindow NodeAI.GraphView.blackboardSearchWindow private
The search window that is used to search for blackboard parameters.
Definition at line 33 of file GraphView.cs.
Referenced by NodeAI.GraphView.AddBlackboardSearchWindow(), and NodeAI.GraphView.GraphView().
currHoveredNode
Node NodeAI.GraphView.currHoveredNode
The node that is currently hovered.
Definition at line 38 of file GraphView.cs.
Referenced by NodeAI.GraphView.HandleMouseLeaveEvent(), NodeAI.GraphView.HandleMouseOverEvent(), and NodeAI.Graph.Update().
exposedProperties
List<NodeData.Property> NodeAI.GraphView.exposedProperties = new List<NodeData.Property>()
List of all exposed properties in the behaviour.
Definition at line 35 of file GraphView.cs.
Referenced by NodeAI.GraphView.AddPropertyToBlackboard(), NodeAI.Serializer.Deserialize(), NodeAI.Graph.GenerateBlackboard(), NodeAI.GraphView.GenerateNode(), NodeAI.GraphView.GenerateParameterNode(), NodeAI.GraphView.HandleDragEndEvent(), and NodeAI.Serializer.Serialize().
querySearchWindow
QuerySearchWindow NodeAI.GraphView.querySearchWindow private
The search window that is used to search for queries.
Definition at line 34 of file GraphView.cs.
Referenced by NodeAI.GraphView.GraphView(), and NodeAI.GraphView.HandleMouseDownEvents().
searchWindow
SearchWindow NodeAI.GraphView.searchWindow private
The search window that is used to search for nodes.
Definition at line 32 of file GraphView.cs.
Referenced by NodeAI.GraphView.AddSearchWindow(), NodeAI.GraphView.GenerateNode(), and NodeAI.GraphView.GraphView().
The documentation for this class was generated from the following file:
Assets/NodeAIv2/Editor/GraphView.cs