Falsepine: Inventory Class Reference
Inventory Class Reference
Classes
class InventorySlot
Public Member Functions
List< Item > GetItems ()
int GetItemIndex (Item item)
void SetSlotsOwner ()
Item TryAddItemToInventory (Item _item)
Add an item to the inventory by reference.
bool CanAddItemToInventory (Item _item)
bool TryAddItemToInventory (string _id, int _amount=1)
Tries to add an item to the inventory by ID.
Item RemoveItemFromInventory (int _index)
void ConvertItemsToInstances ()
Convert all items to instances.
string GetSaveFolderPath (int saveSlot=0)
Gets the save FOLDER path for this inventory.
string GetSaveFilePath ()
Gets the save FILE path for this inventory.
void SaveInventory ()
Saves this inventory to file.
void LoadInventory ()
Loads this inventory from file.
void DeleteSaveFile ()
Delete save file
void ClearInventory ()
Clears all items from the inventory.
void ValidateID ()
Validates the ID of the inventory.
Static Public Member Functions
static string GetInventoryFolder (int saveSlot=0)
static void ValidateIDs (Inventory _selectedInventory=null)
Validates all inventory IDs.
Static Public Attributes
static List< Inventory > allInventories = new List<Inventory>()
Properties
string id [get, set]
List< InventorySlot > slots [get, set]
Private Member Functions
void Awake ()
void OnDestroy ()
void Start ()
Static Private Member Functions
static void AddInventory (Inventory inventory)
Adds this inventory to the inventory list.
static void RemoveInventory (Inventory inventory)
Removes this inventory from the inventory list.
Private Attributes
string m_id = ""
List< InventorySlot > m_slots = new List<InventorySlot>()
Detailed Description
Definition at line 15 of file Inventory.cs.
Member Function Documentation
AddInventory()
static void Inventory.AddInventory (Inventory inventory) inline static private
Adds this inventory to the inventory list.
Definition at line 474 of file Inventory.cs.
Awake()
void Inventory.Awake () inline private
Definition at line 19 of file Inventory.cs.
CanAddItemToInventory()
bool Inventory.CanAddItemToInventory (Item _item) inline
Definition at line 226 of file Inventory.cs.
ClearInventory()
void Inventory.ClearInventory () inline
Clears all items from the inventory.
Definition at line 440 of file Inventory.cs.
Referenced by LoadInventory(), and Console.TrySendCommand().
ConvertItemsToInstances()
void Inventory.ConvertItemsToInstances () inline
Convert all items to instances.
Definition at line 287 of file Inventory.cs.
References Item.CreateInstance().
DeleteSaveFile()
void Inventory.DeleteSaveFile () inline
Delete save file
Definition at line 429 of file Inventory.cs.
References GetSaveFilePath().
GetInventoryFolder()
static string Inventory.GetInventoryFolder (int saveSlot = 0) inline static
Definition at line 300 of file Inventory.cs.
GetItemIndex()
int Inventory.GetItemIndex (Item item) inline
Definition at line 145 of file Inventory.cs.
GetItems()
List< Item > Inventory.GetItems () inline
Definition at line 128 of file Inventory.cs.
GetSaveFilePath()
string Inventory.GetSaveFilePath () inline
Gets the save FILE path for this inventory.
Definition at line 315 of file Inventory.cs.
References GetSaveFolderPath().
Referenced by DeleteSaveFile(), LoadInventory(), and SaveInventory().
GetSaveFolderPath()
string Inventory.GetSaveFolderPath (int saveSlot = 0) inline
Gets the save FOLDER path for this inventory.
Definition at line 307 of file Inventory.cs.
Referenced by GetSaveFilePath(), LoadInventory(), and SaveInventory().
LoadInventory()
void Inventory.LoadInventory () inline
Loads this inventory from file.
Definition at line 372 of file Inventory.cs.
References ClearInventory(), Item.GetInstanceSavePath(), GetSaveFilePath(), GetSaveFolderPath(), and Item.Load().
Referenced by Console.TrySendCommand().
OnDestroy()
void Inventory.OnDestroy () inline private
Definition at line 28 of file Inventory.cs.
RemoveInventory()
static void Inventory.RemoveInventory (Inventory inventory) inline static private
Removes this inventory from the inventory list.
Definition at line 488 of file Inventory.cs.
RemoveItemFromInventory()
Item Inventory.RemoveItemFromInventory (int _index) inline
Definition at line 273 of file Inventory.cs.
SaveInventory()
void Inventory.SaveInventory () inline
Saves this inventory to file.
Definition at line 323 of file Inventory.cs.
References Item.GetInstanceFileName(), Item.GetInstanceSavePath(), GetSaveFilePath(), GetSaveFolderPath(), and Item.Save().
Referenced by Console.TrySendCommand().
SetSlotsOwner()
void Inventory.SetSlotsOwner () inline
Definition at line 177 of file Inventory.cs.
Start()
void Inventory.Start () inline private
Definition at line 32 of file Inventory.cs.
TryAddItemToInventory() [1/2]
Item Inventory.TryAddItemToInventory (Item _item) inline
Add an item to the inventory by reference.
Definition at line 188 of file Inventory.cs.
References Inventory.InventorySlot.TryAddItemToSlot().
Referenced by TryAddItemToInventory(), and Console.TrySendCommand().
TryAddItemToInventory() [2/2]
bool Inventory.TryAddItemToInventory (string _id, int _amount = 1) inline
Tries to add an item to the inventory by ID.
Definition at line 260 of file Inventory.cs.
References Item.CreateInstance(), ItemDatabase.GetItem(), and TryAddItemToInventory().
ValidateID()
void Inventory.ValidateID () inline
Validates the ID of the inventory.
Definition at line 451 of file Inventory.cs.
ValidateIDs()
static void Inventory.ValidateIDs (Inventory _selectedInventory = null) inline static
Validates all inventory IDs.
Definition at line 500 of file Inventory.cs.
References ValidateIDs().
Referenced by ValidateIDs().
Member Data Documentation
allInventories
List<Inventory> Inventory.allInventories = new List<Inventory>() static
Definition at line 17 of file Inventory.cs.
m_id
string Inventory.m_id = "" private
Definition at line 143 of file Inventory.cs.
m_slots
List<InventorySlot> Inventory.m_slots = new List<InventorySlot>() private
Definition at line 170 of file Inventory.cs.
Property Documentation
id
string Inventory.id get set
Definition at line 160 of file Inventory.cs.
slots
List<InventorySlot> Inventory.slots get set
Definition at line 171 of file Inventory.cs.
The documentation for this class was generated from the following file:
Assets/ItemDatabaseTool/Scripts/Inventory.cs