Falsepine: AimZone Class Reference
AimZone Class Reference
Classes
struct Corners
Public Member Functions
Corners GetWorldCorners ()
Get corners of the aim zone in world space
Corners GetLocalCorners ()
Get corners of the aim zone in local space
void SetCorners (Corners _corners)
Sets the corners of the aim zone using world space coordinates
void SetCorners (Vector3 _frontLeft, Vector3 _frontRight, Vector3 _backRight, Vector3 _backLeft)
Sets the corners of the aim zone using world space coordinates
void SetColors (Color _flColor, Color _frColor, Color _brColor, Color _blColor)
void UpdateMesh ()
Update the actual mesh of the aim zone (the quad)
float CalcDmgFalloff (Vector2 _uv)
void Hide ()
void Show ()
Static Public Member Functions
static bool operator== (AimZone a, AimZone b)
static bool operator!= (AimZone a, AimZone b)
Public Attributes
Vector2 uv_fl = new Vector2(-1, 1)
Vector2 uv_fr = new Vector2(1, 1)
Vector2 uv_br = new Vector2(0.1f, 0.1f)
Vector2 uv_bl = new Vector2(-0.1f, 0.1f)
Properties
Vector3 m_fl [get, set]
Vector3 m_fr [get, set]
Vector3 m_br [get, set]
Vector3 m_bl [get, set]
Vector3 fl [get]
Vector3 fr [get]
Vector3 br [get]
Vector3 bl [get]
Private Member Functions
void Awake ()
void Update ()
Private Attributes
Mesh m_mesh
MeshRenderer m_meshRenderer
MeshFilter m_meshFilter
Corners m_corners
Corners m_fallOffCorners
Detailed Description
Definition at line 5 of file AimZone.cs.
Member Function Documentation
Awake()
void AimZone.Awake () inline private
Definition at line 98 of file AimZone.cs.
CalcDmgFalloff()
float AimZone.CalcDmgFalloff (Vector2 _uv) inline
Definition at line 253 of file AimZone.cs.
GetLocalCorners()
Corners AimZone.GetLocalCorners () inline
Get corners of the aim zone in local space
Returns
Corners Struct
Definition at line 182 of file AimZone.cs.
Referenced by UpdateMesh().
GetWorldCorners()
Corners AimZone.GetWorldCorners () inline
Get corners of the aim zone in world space
Returns
Corners struct
Definition at line 168 of file AimZone.cs.
Hide()
void AimZone.Hide () inline
Definition at line 259 of file AimZone.cs.
operator!=()
static bool AimZone.operator!= (AimZone a, AimZone b) inline static
Definition at line 92 of file AimZone.cs.
operator==()
static bool AimZone.operator== (AimZone a, AimZone b) inline static
Definition at line 77 of file AimZone.cs.
SetColors()
void AimZone.SetColors (Color _flColor, Color _frColor, Color _brColor, Color _blColor) inline
Definition at line 218 of file AimZone.cs.
SetCorners() [1/2]
void AimZone.SetCorners (Corners _corners) inline
Sets the corners of the aim zone using world space coordinates
Parameters
_corners A corners struct containing the points
Definition at line 196 of file AimZone.cs.
References UpdateMesh().
Referenced by SetCorners().
SetCorners() [2/2]
void AimZone.SetCorners (Vector3 _frontLeft, Vector3 _frontRight, Vector3 _backRight, Vector3 _backLeft) inline
Sets the corners of the aim zone using world space coordinates
Parameters
_frontLeft
_frontRight
_backRight
_backLeft
Definition at line 213 of file AimZone.cs.
References SetCorners().
Show()
void AimZone.Show () inline
Definition at line 264 of file AimZone.cs.
Update()
void AimZone.Update () inline private
Definition at line 149 of file AimZone.cs.
UpdateMesh()
void AimZone.UpdateMesh () inline
Update the actual mesh of the aim zone (the quad)
Definition at line 231 of file AimZone.cs.
References GetLocalCorners().
Referenced by SetCorners().
Member Data Documentation
m_corners
Corners AimZone.m_corners private
Definition at line 63 of file AimZone.cs.
m_fallOffCorners
Corners AimZone.m_fallOffCorners private
Definition at line 64 of file AimZone.cs.
m_mesh
Mesh AimZone.m_mesh private
Definition at line 7 of file AimZone.cs.
m_meshFilter
MeshFilter AimZone.m_meshFilter private
Definition at line 9 of file AimZone.cs.
m_meshRenderer
MeshRenderer AimZone.m_meshRenderer private
Definition at line 8 of file AimZone.cs.
uv_bl
Vector2 AimZone.uv_bl = new Vector2(-0.1f, 0.1f)
Definition at line 20 of file AimZone.cs.
uv_br
Vector2 AimZone.uv_br = new Vector2(0.1f, 0.1f)
Definition at line 19 of file AimZone.cs.
uv_fl
Vector2 AimZone.uv_fl = new Vector2(-1, 1)
Definition at line 17 of file AimZone.cs.
uv_fr
Vector2 AimZone.uv_fr = new Vector2(1, 1)
Definition at line 18 of file AimZone.cs.
Property Documentation
bl
Vector3 AimZone.bl get
Definition at line 74 of file AimZone.cs.
br
Vector3 AimZone.br get
Definition at line 73 of file AimZone.cs.
fl
Vector3 AimZone.fl get
Definition at line 71 of file AimZone.cs.
fr
Vector3 AimZone.fr get
Definition at line 72 of file AimZone.cs.
m_bl
Vector3 AimZone.m_bl get set private
Definition at line 69 of file AimZone.cs.
m_br
Vector3 AimZone.m_br get set private
Definition at line 68 of file AimZone.cs.
m_fl
Vector3 AimZone.m_fl get set private
Definition at line 66 of file AimZone.cs.
m_fr
Vector3 AimZone.m_fr get set private
Definition at line 67 of file AimZone.cs.
The documentation for this class was generated from the following file:
Assets/AimZone.cs