Falsepine: NodeAI.SearchWindow Class Reference
NodeAI.SearchWindow Class Reference
A search window provider for the NodeAI graph.
Public Member Functions
void Init (GraphView graphView)
Initializes the search window provider.
void SetSelectedNode (Node node)
Sets the selected node.
List< SearchTreeEntry > CreateSearchTree (SearchWindowContext context)
Creates the search tree for the search window.
bool OnSelectEntry (SearchTreeEntry entry, SearchWindowContext context)
Creates a new node.
Private Member Functions
Type[] GetInheritedClasses (Type MyType)
Gets all child classes of the given type.
Private Attributes
GraphView graphView
Node selectedNode
Detailed Description
A search window provider for the NodeAI graph.
Definition at line 28 of file SearchWindow.cs.
Member Function Documentation
CreateSearchTree()
List< SearchTreeEntry > NodeAI.SearchWindow.CreateSearchTree (SearchWindowContext context) inline
Creates the search tree for the search window.
Parameters
context The search window context.
Returns
The search tree.
Definition at line 66 of file SearchWindow.cs.
References NodeAI.SearchWindow.GetInheritedClasses().
GetInheritedClasses()
Type[] NodeAI.SearchWindow.GetInheritedClasses (Type MyType) inline private
Gets all child classes of the given type.
Parameters
MyType The type to get the child classes of.
Returns
A list of child classes.
Definition at line 56 of file SearchWindow.cs.
Referenced by NodeAI.SearchWindow.CreateSearchTree().
Init()
void NodeAI.SearchWindow.Init (GraphView graphView) inline
Initializes the search window provider.
Definition at line 37 of file SearchWindow.cs.
Referenced by NodeAI.GraphView.GraphView().
OnSelectEntry()
bool NodeAI.SearchWindow.OnSelectEntry (SearchTreeEntry entry, SearchWindowContext context) inline
Creates a new node.
Parameters
context The search window context.
Returns
Boolean indicating if the node was created.
Definition at line 219 of file SearchWindow.cs.
References NodeAI.GraphView.ContextCreateNode().
SetSelectedNode()
void NodeAI.SearchWindow.SetSelectedNode (Node node) inline
Sets the selected node.
Definition at line 45 of file SearchWindow.cs.
Referenced by NodeAI.GraphView.GenerateNode().
Member Data Documentation
graphView
GraphView NodeAI.SearchWindow.graphView private
Definition at line 30 of file SearchWindow.cs.
selectedNode
Node NodeAI.SearchWindow.selectedNode private
Definition at line 32 of file SearchWindow.cs.
The documentation for this class was generated from the following file:
Assets/NodeAIv2/Editor/SearchWindow.cs