Falsepine: NodeAI.Serializer Class Reference
NodeAI.Serializer Class Reference
Responsible for Serializing and Deserializing NodeAI Graphs
Public Member Functions
void Serialize (NodeAI_Behaviour nodeAI_Behaviour)
Serializes the graph.
void Deserialize (NodeAI_Behaviour nodeAI_Behaviour)
Deserializes the graph.
Static Public Member Functions
static Serializer GetInstance (GraphView target)
Initializes the serializer.
Properties
List< Edge > edges [get]
List< Node > nodes [get]
Private Attributes
GraphView target
Detailed Description
Responsible for Serializing and Deserializing NodeAI Graphs
This class is used to serialize and deserialize NodeAI Graphs.
Definition at line 31 of file Serializer.cs.
Member Function Documentation
Deserialize()
void NodeAI.Serializer.Deserialize (NodeAI_Behaviour nodeAI_Behaviour) inline
Deserializes the graph.
Definition at line 196 of file Serializer.cs.
References NodeAI.GraphView.AddPropertyToBlackboard(), NodeAI.GraphView.blackboard, NodeAI.GraphView.CreateGroup(), NodeAI.GraphView.exposedProperties, NodeAI.GraphView.GenerateNode(), and NodeAI.NodeData.Property< T >.GUID.
Referenced by NodeAI.Graph.CreateNewBehaviour(), NodeAI.Graph.GenerateToolbar(), NodeAI.Graph.OnEnable(), and NodeAI.Graph.OnOpenAsset().
GetInstance()
static Serializer NodeAI.Serializer.GetInstance (GraphView target) inline static
Initializes the serializer.
Definition at line 42 of file Serializer.cs.
Referenced by NodeAI.Graph.CreateNewBehaviour(), NodeAI.Graph.GenerateToolbar(), NodeAI.Graph.OnEnable(), and NodeAI.Graph.OnOpenAsset().
Serialize()
void NodeAI.Serializer.Serialize (NodeAI_Behaviour nodeAI_Behaviour) inline
Serializes the graph.
Definition at line 54 of file Serializer.cs.
References NodeAI.GraphView.exposedProperties, NodeAI.NodeData.GUID, and NodeAI.NodeData.NodeGroup.title.
Member Data Documentation
target
GraphView NodeAI.Serializer.target private
Definition at line 33 of file Serializer.cs.
Property Documentation
edges
List<Edge> NodeAI.Serializer.edges get private
Definition at line 35 of file Serializer.cs.
nodes
List<Node> NodeAI.Serializer.nodes get private
Definition at line 36 of file Serializer.cs.
The documentation for this class was generated from the following file:
Assets/NodeAIv2/Editor/Serializer.cs