Falsepine: NodeAI.SeekCoverFrom Class Reference
NodeAI.SeekCoverFrom Class Reference
A Node that seeks cover from a target.
Public Member Functions
SeekCoverFrom ()
Constructor.
override void OnInit ()
Initializes the node.
override NodeData.State Eval (NodeAI_Agent agent, NodeTree.Leaf current)
Evaluates the node.
Public Member Functions inherited from NodeAI.ActionBase
override NodeData.State Eval (NodeAI_Agent agent, NodeTree.Leaf current)
Eval is called when the node is evaluated, and contains all of the logic for the node.
Public Member Functions inherited from NodeAI.RuntimeBase
void OnEnable ()
void RepopulateProperties (List< NodeData.SerializableProperty > properties)
Repopulates properties that may have gotted destroyed in serialisation.
void AddProperty< T > (string name, T initialValue)
Adds a property field to the node.
void SetProperty< T > (string name, T value)
Sets the value of a property field.
void SetProperty (string name, Object value, System.Type type)
Sets the property of a value field as an Object type.
void SetPropertyGUID (string name, string GUID)
Sets the GUID of a property field.
void SetPropertyParamReference (string name, string paramReference)
Sets the Parameter reference of a Property
T GetProperty< T > (string name)
Gets the value of a property field.
List< NodeData.Property > GetProperties ()
Gets all the properties of a node.
List< NodeData.SerializableProperty > GetSerializableProperties ()
Gets all properties of a node as SerializableProperties.
List< NodeData.SerializableProperty > GetPropertiesWhereParamReference (string paramReference)
Gets all properties with a specific parameter reference.
virtual NodeData.State Eval (NodeAI_Agent agent, NodeTree.Leaf current)
Eval is called when the node is evaluated, and contains all of the logic for the node.
virtual void DrawGizmos (NodeAI_Agent agent)
Draw Gizmos is called when the Agent draws gizmos.
virtual void OnInit ()
OnInit is called whenever a node begins running.
void Init (NodeTree.Leaf current)
Initialises the node and its children.
Private Member Functions
Vector3 GetClosestCoverPoint (NodeAI_Agent agent, GameObject coverFrom)
Gets the closest cover point to the agent.
Private Attributes
NavMeshAgent navAgent
The NavMeshAgent of the agent.
GameObject coverFrom
The target to seek cover from.
Vector3 currCoverPoint
The current cover point.
bool initialized = false
Whether or not the node has been initialized.
Additional Inherited Members
Public Attributes inherited from NodeAI.RuntimeBase
NodeData.State state
The state of the node.
string tooltip = ""
The tooltip of the node.
Detailed Description
A Node that seeks cover from a target.
This node is part of the Demo for NodeAI.
Definition at line 27 of file SeekCoverFrom.cs.
Constructor & Destructor Documentation
SeekCoverFrom()
NodeAI.SeekCoverFrom.SeekCoverFrom () inline
Constructor.
Definition at line 38 of file SeekCoverFrom.cs.
References NodeAI.RuntimeBase.tooltip.
Member Function Documentation
Eval()
override NodeData.State NodeAI.SeekCoverFrom.Eval (NodeAI_Agent agent, NodeTree.Leaf current) inline virtual
Evaluates the node.
Parameters
agent The agent to evaluate the node for.
current The current leaf of the node tree.
Returns
The state of the node.
Reimplemented from NodeAI.RuntimeBase.
Definition at line 62 of file SeekCoverFrom.cs.
References NodeAI.SeekCoverFrom.coverFrom, NodeAI.SeekCoverFrom.currCoverPoint, NodeAI.SeekCoverFrom.GetClosestCoverPoint(), NodeAI.SeekCoverFrom.initialized, NodeAI.SeekCoverFrom.navAgent, and NodeAI.RuntimeBase.state.
GetClosestCoverPoint()
Vector3 NodeAI.SeekCoverFrom.GetClosestCoverPoint (NodeAI_Agent agent, GameObject coverFrom) inline private
Gets the closest cover point to the agent.
Parameters
agent The current agent.
coverFrom The Object the agent is taking cover from.
Returns
Definition at line 134 of file SeekCoverFrom.cs.
References NodeAI.SeekCoverFrom.coverFrom, and Cover.GetAvailableCoverPoints().
Referenced by NodeAI.SeekCoverFrom.Eval().
OnInit()
override void NodeAI.SeekCoverFrom.OnInit () inline virtual
Initializes the node.
Reimplemented from NodeAI.RuntimeBase.
Definition at line 51 of file SeekCoverFrom.cs.
References NodeAI.SeekCoverFrom.initialized.
Member Data Documentation
coverFrom
GameObject NodeAI.SeekCoverFrom.coverFrom private
The target to seek cover from.
Definition at line 30 of file SeekCoverFrom.cs.
Referenced by NodeAI.SeekCoverFrom.Eval(), and NodeAI.SeekCoverFrom.GetClosestCoverPoint().
currCoverPoint
Vector3 NodeAI.SeekCoverFrom.currCoverPoint private
The current cover point.
Definition at line 31 of file SeekCoverFrom.cs.
Referenced by NodeAI.SeekCoverFrom.Eval().
initialized
bool NodeAI.SeekCoverFrom.initialized = false private
Whether or not the node has been initialized.
Definition at line 33 of file SeekCoverFrom.cs.
Referenced by NodeAI.SeekCoverFrom.Eval(), and NodeAI.SeekCoverFrom.OnInit().
navAgent
NavMeshAgent NodeAI.SeekCoverFrom.navAgent private
The NavMeshAgent of the agent.
Definition at line 29 of file SeekCoverFrom.cs.
Referenced by NodeAI.SeekCoverFrom.Eval().
The documentation for this class was generated from the following file:
Assets/NodeAIv2/Runtime/Actions/SeekCoverFrom.cs