Falsepine: NodeAI.Graph Class Reference
NodeAI.Graph Class Reference
The EditorWindow for the NodeAI Graph editor.
Static Public Member Functions
static void OpenGraphWindow ()
This function is called when the Graph editor is opened.
static bool OnOpenAsset (int instanceId, int line)
This function is called when a NodeAI_Behaviour asset is opened in the project view.
Private Member Functions
void OnEnable ()
This function is called when the Graph editor is opened.
void Update ()
This function is called every frame.
void CreateNewBehaviour ()
This function is used to create a new NodeAI_Behaviour asset.
void OnDisable ()
Called when the editor window is closed.
void GenerateToolbar ()
This function is used to generate the toolbar for the editor window.
void GenerateBlackboard ()
This function is used to generate the Blackboard for the editor window.
Private Attributes
GraphView graphView
The GraphView that is currently being edited.
NodeAI_Behaviour behaviour
The NodeAI_Behaviour that is currently being edited.
NodeAI_Behaviour runtimeBehaviour
The NodeAI_Behaviour that has been selected at runtime, used for visual debugging.
ObjectField behaviourField
The ObjectField that is used to select a NodeAI_Behaviour.
float timeSinceLastDraw = 0f
int lastChildIndex = 0
Detailed Description
The EditorWindow for the NodeAI Graph editor.
This class is used to create a GraphView and handle all of the events that occur in the GraphView.
This class is also used to create a new NodeAI_Behaviour and save it to the project.
This class is also used to load a NodeAI_Behaviour from the project.
Definition at line 39 of file Graph.cs.
Member Function Documentation
CreateNewBehaviour()
void NodeAI.Graph.CreateNewBehaviour () inline private
This function is used to create a new NodeAI_Behaviour asset.
Definition at line 216 of file Graph.cs.
References NodeAI.GraphView.AddEntryNode(), NodeAI.Graph.behaviour, NodeAI.Serializer.Deserialize(), NodeAI.Serializer.GetInstance(), and NodeAI.Graph.graphView.
Referenced by NodeAI.Graph.GenerateToolbar().
GenerateBlackboard()
void NodeAI.Graph.GenerateBlackboard () inline private
This function is used to generate the Blackboard for the editor window.
Definition at line 289 of file Graph.cs.
References NodeAI.GraphView.AddBlackboardSearchWindow(), NodeAI.GraphView.blackboard, NodeAI.GraphView.exposedProperties, and NodeAI.Graph.graphView.
Referenced by NodeAI.Graph.OnEnable().
GenerateToolbar()
void NodeAI.Graph.GenerateToolbar () inline private
This function is used to generate the toolbar for the editor window.
Definition at line 245 of file Graph.cs.
References NodeAI.Graph.behaviour, NodeAI.Graph.behaviourField, NodeAI.Graph.CreateNewBehaviour(), NodeAI.Serializer.Deserialize(), NodeAI.Serializer.GetInstance(), and NodeAI.Graph.graphView.
Referenced by NodeAI.Graph.OnEnable().
OnDisable()
void NodeAI.Graph.OnDisable () inline private
Called when the editor window is closed.
Definition at line 236 of file Graph.cs.
References NodeAI.Graph.graphView.
OnEnable()
void NodeAI.Graph.OnEnable () inline private
This function is called when the Graph editor is opened.
Definition at line 89 of file Graph.cs.
References NodeAI.Graph.behaviour, NodeAI.Serializer.Deserialize(), NodeAI.Graph.GenerateBlackboard(), NodeAI.Graph.GenerateToolbar(), NodeAI.Serializer.GetInstance(), and NodeAI.Graph.graphView.
OnOpenAsset()
static bool NodeAI.Graph.OnOpenAsset (int instanceId, int line) inline static
This function is called when a NodeAI_Behaviour asset is opened in the project view.
It is responsible for opening the NodeAI Graph Editor window and loading the selected NodeAI_Behaviour asset.
Parameters
instanceId
line
Returns
Definition at line 71 of file Graph.cs.
References NodeAI.Graph.behaviour, NodeAI.Graph.behaviourField, NodeAI.Serializer.Deserialize(), NodeAI.Serializer.GetInstance(), and NodeAI.Graph.graphView.
OpenGraphWindow()
static void NodeAI.Graph.OpenGraphWindow () inline static
This function is called when the Graph editor is opened.
Definition at line 54 of file Graph.cs.
Update()
void NodeAI.Graph.Update () inline private
This function is called every frame.
Definition at line 105 of file Graph.cs.
References NodeAI.NodeAI_Agent.AI_Behaviour, NodeAI.Graph.behaviour, NodeAI.GraphView.currHoveredNode, NodeAI.Graph.graphView, NodeAI.NodeData.GUID, NodeAI.NodeAI_Behaviour.nodeData, NodeAI.Node.nodeType, NodeAI.Node.outputPort, NodeAI.Graph.runtimeBehaviour, NodeAI.NodeData.runtimeLogic, and NodeAI.RuntimeBase.state.
Member Data Documentation
behaviour
NodeAI_Behaviour NodeAI.Graph.behaviour private
The NodeAI_Behaviour that is currently being edited.
Definition at line 42 of file Graph.cs.
Referenced by NodeAI.Graph.CreateNewBehaviour(), NodeAI.Graph.GenerateToolbar(), NodeAI.Graph.OnEnable(), NodeAI.Graph.OnOpenAsset(), and NodeAI.Graph.Update().
behaviourField
ObjectField NodeAI.Graph.behaviourField private
The ObjectField that is used to select a NodeAI_Behaviour.
Definition at line 45 of file Graph.cs.
Referenced by NodeAI.Graph.GenerateToolbar(), and NodeAI.Graph.OnOpenAsset().
graphView
GraphView NodeAI.Graph.graphView private
The GraphView that is currently being edited.
Definition at line 41 of file Graph.cs.
Referenced by NodeAI.Graph.CreateNewBehaviour(), NodeAI.Graph.GenerateBlackboard(), NodeAI.Graph.GenerateToolbar(), NodeAI.Graph.OnDisable(), NodeAI.Graph.OnEnable(), NodeAI.Graph.OnOpenAsset(), and NodeAI.Graph.Update().
lastChildIndex
int NodeAI.Graph.lastChildIndex = 0 private
Definition at line 48 of file Graph.cs.
runtimeBehaviour
NodeAI_Behaviour NodeAI.Graph.runtimeBehaviour private
The NodeAI_Behaviour that has been selected at runtime, used for visual debugging.
Definition at line 43 of file Graph.cs.
Referenced by NodeAI.Graph.Update().
timeSinceLastDraw
float NodeAI.Graph.timeSinceLastDraw = 0f private
Definition at line 47 of file Graph.cs.
The documentation for this class was generated from the following file:
Assets/NodeAIv2/Editor/Graph.cs