Falsepine: NodeAI.QuerySearchWindow Class Reference
NodeAI.QuerySearchWindow Class Reference
The search window for queries.
Public Member Functions
void Init (GraphView graphView)
This function is called when the search window is opened.
void PopulateSearchTreeRecursively (List< SearchTreeEntry > searchTree, NamespaceParser.NamespaceEntry entry, int depth=0)
This method is used to recursively populate the search window.
List< SearchTreeEntry > CreateSearchTree (SearchWindowContext context)
This method is used to create a search window.
bool OnSelectEntry (SearchTreeEntry entry, SearchWindowContext context)
This method is called when an entry is selected in the search window.
Private Member Functions
Type[] GetInheritedClasses (Type MyType)
Used to get all child classes of a given type.
Private Attributes
GraphView graphView
The GraphView that is currently being searched.
Detailed Description
The search window for queries.
Definition at line 28 of file QuerySearchWindow.cs.
Member Function Documentation
CreateSearchTree()
List< SearchTreeEntry > NodeAI.QuerySearchWindow.CreateSearchTree (SearchWindowContext context) inline
This method is used to create a search window.
Parameters
context
Returns
Definition at line 80 of file QuerySearchWindow.cs.
References NodeAI.QuerySearchWindow.GetInheritedClasses(), NodeAI.QuerySearchWindow.PopulateSearchTreeRecursively(), and NodeAI.NamespaceParser.TreeFromTypes().
GetInheritedClasses()
Type[] NodeAI.QuerySearchWindow.GetInheritedClasses (Type MyType) inline private
Used to get all child classes of a given type.
Parameters
MyType The type to check.
Returns
An array of all child types of the provided type.
Definition at line 47 of file QuerySearchWindow.cs.
Referenced by NodeAI.QuerySearchWindow.CreateSearchTree().
Init()
void NodeAI.QuerySearchWindow.Init (GraphView graphView) inline
This function is called when the search window is opened.
Parameters
graphView
Definition at line 37 of file QuerySearchWindow.cs.
References NodeAI.QuerySearchWindow.graphView.
Referenced by NodeAI.GraphView.GraphView().
OnSelectEntry()
bool NodeAI.QuerySearchWindow.OnSelectEntry (SearchTreeEntry entry, SearchWindowContext context) inline
This method is called when an entry is selected in the search window.
Parameters
entry
context
Returns
Definition at line 102 of file QuerySearchWindow.cs.
References NodeAI.GraphView.GenerateQueryNode(), and NodeAI.QuerySearchWindow.graphView.
PopulateSearchTreeRecursively()
void NodeAI.QuerySearchWindow.PopulateSearchTreeRecursively (List< SearchTreeEntry > searchTree, NamespaceParser.NamespaceEntry entry, int depth = 0) inline
This method is used to recursively populate the search window.
Parameters
searchTree The SearchTree to populate.
entry The Type to use as the Entry point.
depth The current recursion depth.
Definition at line 58 of file QuerySearchWindow.cs.
References NodeAI.QuerySearchWindow.PopulateSearchTreeRecursively().
Referenced by NodeAI.QuerySearchWindow.CreateSearchTree(), and NodeAI.QuerySearchWindow.PopulateSearchTreeRecursively().
Member Data Documentation
graphView
GraphView NodeAI.QuerySearchWindow.graphView private
The GraphView that is currently being searched.
Definition at line 30 of file QuerySearchWindow.cs.
Referenced by NodeAI.QuerySearchWindow.Init(), and NodeAI.QuerySearchWindow.OnSelectEntry().
The documentation for this class was generated from the following file:
Assets/NodeAIv2/Editor/QuerySearchWindow.cs