Falsepine: SceneTransitionManager Class Reference
SceneTransitionManager Class Reference
Script responsible for handling player entry and exit from mission scenes.
Public Member Functions
void UnlockNextScene ()
Allows the player to move to the next scene.
void Update ()
Checks if the player can move to the next scene.
IEnumerator FadeToBlack (string scene)
Coroutine to fade the screen to black and load the next scene.
Public Attributes
Transform exitTransform
The transform of the exit point.
Rect exitBounds
The bounds of the exit point.
Private Member Functions
Rect ScaleRect (Rect rect, Vector3 scale)
Scales a rectangle.
Rect RotateRect (Rect rect, float angle)
Rotates a rectangle.
Vector2 RotatePoint (Vector2 point, float angle)
Rotates a point around a center point.
void OnDrawGizmos ()
Draws the bounds of the exit point.
Private Attributes
Rect bounds
bool canMoveToNextScene = true
Whether or not the player can move to the next scene.
Detailed Description
Script responsible for handling player entry and exit from mission scenes.
Definition at line 10 of file SceneTransitionManager.cs.
Member Function Documentation
FadeToBlack()
IEnumerator SceneTransitionManager.FadeToBlack (string scene) inline
Coroutine to fade the screen to black and load the next scene.
Parameters
scene The name of the Scene to load
Attention
This uses the Fade object already present in the UI, but does not interact with the script which is meant to control this fade ui. This is a temporary solution, and a more robust solution should be discussed with Keane.
Definition at line 85 of file SceneTransitionManager.cs.
Referenced by Update().
OnDrawGizmos()
void SceneTransitionManager.OnDrawGizmos () inline private
Draws the bounds of the exit point.
Definition at line 148 of file SceneTransitionManager.cs.
References canMoveToNextScene, exitBounds, exitTransform, RotateRect(), and ScaleRect().
RotatePoint()
Vector2 SceneTransitionManager.RotatePoint (Vector2 point, float angle) inline private
Rotates a point around a center point.
Parameters
point
angle
Returns
Definition at line 132 of file SceneTransitionManager.cs.
Referenced by RotateRect().
RotateRect()
Rect SceneTransitionManager.RotateRect (Rect rect, float angle) inline private
Rotates a rectangle.
Parameters
rect
angle
Returns
Definition at line 116 of file SceneTransitionManager.cs.
References RotatePoint().
Referenced by OnDrawGizmos(), and Update().
ScaleRect()
Rect SceneTransitionManager.ScaleRect (Rect rect, Vector3 scale) inline private
Scales a rectangle.
Parameters
rect
scale
Returns
Definition at line 105 of file SceneTransitionManager.cs.
Referenced by OnDrawGizmos(), and Update().
UnlockNextScene()
void SceneTransitionManager.UnlockNextScene () inline
Allows the player to move to the next scene.
Definition at line 23 of file SceneTransitionManager.cs.
References canMoveToNextScene.
Update()
void SceneTransitionManager.Update () inline
Checks if the player can move to the next scene.
Todo:
Add in a transition sound effect.
Bug:
There may be some sort of issue with the bounds calculation not being correct, causing the trigger zone to not be where the gizmo shows. this needs further testing to confirm.
Definition at line 44 of file SceneTransitionManager.cs.
References canMoveToNextScene, MissionSequencer.currentSequence, exitBounds, exitTransform, FadeToBlack(), RotateRect(), and ScaleRect().
Member Data Documentation
bounds
Rect SceneTransitionManager.bounds private
Definition at line 16 of file SceneTransitionManager.cs.
canMoveToNextScene
bool SceneTransitionManager.canMoveToNextScene = true private
Whether or not the player can move to the next scene.
Definition at line 18 of file SceneTransitionManager.cs.
Referenced by OnDrawGizmos(), UnlockNextScene(), and Update().
exitBounds
Rect SceneTransitionManager.exitBounds
The bounds of the exit point.
Definition at line 14 of file SceneTransitionManager.cs.
Referenced by OnDrawGizmos(), and Update().
exitTransform
Transform SceneTransitionManager.exitTransform
The transform of the exit point.
Definition at line 13 of file SceneTransitionManager.cs.
Referenced by OnDrawGizmos(), and Update().
The documentation for this class was generated from the following file:
Assets/Scripts/Missions/SceneTransitionManager.cs