# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-docs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@1.9.4
        
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to GitHub Pages
  # You may pin to the exact commit or the version.
  # uses: tsunematsu21/actions-publish-gh-pages@c04b531c52b8f9d25c596bc6e6a7ddc116b2f3f8
  uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
  with:
    # The name of the directory that containing the content to be published
    dir: ./docs
    # The name of the remote branch that publishing source for GitHub Pages site
    branch: main
    # The remote repository that publishing source for GitHub Pages site, defaults to current repo and is formatted like 'user/repo-name'
    repo: Voyager-Softworks/Falsepine_Production
    # The personal access token that authorize repo access
    token: ${{ secrets.GITHUB_TOKEN }}
      
      
