# Simple workflow for deploying static content to GitHub Pages
name: Documentation Updater Process

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  update-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Sparse Checkout
        # You may pin to the exact commit or the version.
        # uses: gogaille/sparse-checkout@3114de9b3cf84c0829fe84222d8ae8d806fbc794
        uses: gogaille/sparse-checkout@v0.1
        with:
          # Git sparse checkout patterns.
          patterns: 'docs/* Doxyfile Assets/Scripts/*'
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Update Doxygen Documentation
        uses: mattnotmitt/doxygen-action@1.9.4
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Documentation for {{ EVENT_PAYLOAD.repository.full_name }} has been updated and deployed successfully! https://voyager-softworks.github.io/Falsepine_Production/index.html'
